[package]
name = "blockdreamer"
version = "0.1.0"
edition = "2021"

[features]
default = ["mainnet"]
mainnet = []
gnosis = []

[dependencies]
futures = "0.3.4"
itertools = "0.10.3"
pathfinding = "3.0.11"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
toml = "0.5"
reqwest = "0.11.11"
serde_json = "1.0.0"

eth2 = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
eth2_network_config = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
sensitive_url = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
slot_clock = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }

[dev-dependencies]
proptest = "1.0.0"

[patch]
[patch.crates-io]
fixed-hash = { git = "https://github.com/paritytech/parity-common", rev="df638ab0885293d21d656dc300d39236b69ce57d" }
eth2_ssz = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
eth2_ssz_types = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
tree_hash = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
eth2_serde_utils = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
eth2_hashing = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
